Abc.MvcWebUI/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Abc.MvcWebUI.Entity;
using Abc.MvcWebUI.Models;

namespace Abc.MvcWebUI.Controllers
{
    [Authorize(Roles="admin")]
    public class OrderController : Controller
    {
        DataContext db = new DataContext();

        // GET: Order
        public ActionResult Index()
        {
            var orders = db.Orders.Select(i => new AdminOrderModel()
            {
                Id = i.Id,
                OrderNumber = i.OrderNumber,
                OrderDate = i.OrderDate,
                OrderState = i.OrderState,
                Total = i.Total,
                Count = i.OrderLines.Count
                
            }).OrderByDescending(i=>i.OrderDate).ToList();

            return View(orders);
        }

        public ActionResult Details(int id)
        {
            var entity = db.Orders
                .Where(i => i.Id == id)
                .Select(i => new OrderDetailsModel()
                {
                    OrderId = i.Id,
                    OrderNumber = i.OrderNumber,
                    Total = i.Total,
                    OrderDate = i.OrderDate,
                    OrderState = i.OrderState,

                    AddressName = i.AddressName,
                    Address = i.Address,
                    City = i.City,
                    Neighborhood = i.Neighborhood,
                    PostCode = i.PostCode,
                    District = i.District,

                    OrderLines = i.OrderLines
                        .Select(a => new OrderLineModel()
                        {
                            ProductId = a.ProductId,
                            ProductName = a.Product.Name.Length > 50 ? a.Product.Name.Substring(0, 47) + "..." : a.Product.Name,
                            Image = a.Product.Image,
                            Quantity = a.Quantity,
                            Price = a.Price

                        }).ToList()
                }).FirstOrDefault();


            return View(entity);

        }


        public ActionResult UpdateOrderState(int OrderId, EnumOrderState OrderState)
        {

            var order = db.Orders.FirstOrDefault(i => i.Id == OrderId);
            if (order !=null)
            {
                order.OrderState = OrderState;
                db.SaveChanges();
                TempData["message"] = "Yor Update is success";

                return RedirectToAction("Details", new {id = OrderId});
            }

            return RedirectToAction("Index");
        }
    }
}

Abc.MvcWebUI/Views/Order/Details.cshtml
@using Abc.MvcWebUI.Entity
@model Abc.MvcWebUI.Models.OrderDetailsModel
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container pb-5" style="background-color: azure">
    <div class="row">
        <div class="col-md-12">
            <h2>Your order Details information</h2>
            <hr />
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">Update Complated</div>
            }
            <dl class="row">
                <dt class="col-md-3">@Html.DisplayNameFor(model => model.OrderState)</dt>
                <dd class="col-md-9">

                    @using (Html.BeginForm("UpdateOrderState", "Order", FormMethod.Post))
                    {
                        @Html.HiddenFor(i => i.OrderId)
                        <dl class="row">
                            <dt class="col-sm-4">
                                @Html.EnumDropDownListFor(i => i.OrderState, "Select Order State", new { @class = "form-control" })
                            </dt>
                            <dd class="col-sm-4">
                                <button type="submit" class="btn btn-outline-success ">Update</button>
                            </dd>
                        </dl>
                    }

                </dd>

                <dt class="col-md-3">@Html.DisplayNameFor(model => model.OrderId)</dt>
                <dd class="col-md-9">@Model.OrderId</dd>

                <dt class="col-md-3">@Html.DisplayNameFor(model => model.OrderNumber)</dt>
                <dd class="col-md-9">@Model.OrderNumber</dd>

                <dt class="col-md-3">@Html.DisplayNameFor(model => model.Total)</dt>
                <dd class="col-md-9">
                    <i class="fas fa-lira-sign"></i>
                    @Model.Total
                </dd>

                <dt class="col-md-3">@Html.DisplayNameFor(model => model.OrderDate)</dt>
                <dd class="col-md-9">@Model.OrderDate</dd>

                <dt class="col-md-3">Address</dt>
                <dd class="col-md-9">
                    @Model.AddressName
                    <hr />
                    @Model.Address
                    <br />
                    @Model.City  -  @Model.Neighborhood   - @Model.District
                    <br />
                    @Model.PostCode
                </dd>

                <dt class="col-md-3">Products</dt>
                <dd class="col-md-9">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <td>Image</td>
                                <td>Product Name</td>
                                <td>Quantity</td>
                                <td>Price</td>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in @Model.OrderLines)
                            {
                                <tr>
                                    <td><img src="/Upload/@item.Image" width="70" /></td>
                                    <td>@item.ProductName</td>
                                    <td>@item.Quantity</td>
                                    <td>
                                        <i class="fas fa-lira-sign"></i>
                                        @item.Price
                                    </td>
                                    <td>
                                        <a href="/Home/Details/@item.ProductId" class="btn btn-primary" target="_blank">Product Details</a>
                                    </td>
                                </tr>

                            }
                        </tbody>

                    </table>
                </dd>
            </dl>

        </div>
    </div>
</div>

Abc.MvcWebUI/Views/Order/Index.cshtml
@model IEnumerable<Abc.MvcWebUI.Models.AdminOrderModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container pb-5">
<h2>Orders Management Panel </h2>
    <hr/>
    <table class="table table-striped table-bordered " style="background-color: azure">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Id)l</th>
                <th>@Html.DisplayNameFor(model => model.OrderNumber)</th>
                <th>@Html.DisplayNameFor(model => model.OrderDate)</th>
                <th>@Html.DisplayNameFor(model => model.OrderState)</th>
                <th>@Html.DisplayNameFor(model=>model.Count)</th>
                <th>@Html.DisplayNameFor(model => model.Total)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.Id</td>
                <td>@item.OrderNumber</td>
                <td>@item.OrderDate</td>
                <td>@item.OrderState</td>
                <td>@item.Count</td>
                <td>@item.Total</td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id } ,new { @class = "btn btn-outline-success btn-sm"})
                </td>
            </tr>



            }
        </tbody>

    </table>



</div>